# Generated by Django 2.2 on 2020-08-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[(2, 'Approved'), (3, 'Rejected'), (4, 'Edited and approved'), (1, 'Pending')], default=1, max_length=255),
        ),
    ]
