# Generated by Django 2.2 on 2020-08-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20200824_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
