# Generated by Django 2.2 on 2020-08-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20200824_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tax_perc',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
